// ReSharper disable UnusedMember.Global
// ReSharper disable InconsistentNaming

#pragma warning disable 1591 // Missing XML comment for publicly visible type or member

using CUE.NET.Devices.Generic.Enums;

namespace CUE.NET.Devices.Keyboard.Enums
{
    /// <summary>
    /// Contains list of all LEDs available for corsair keyboards.
    /// </summary>
    public static class CorsairKeyboardLedId
    {
        public const CorsairLedId Invalid = CorsairLedId.Invalid;
        public const CorsairLedId Escape = CorsairLedId.Escape;
        public const CorsairLedId F1 = CorsairLedId.F1;
        public const CorsairLedId F2 = CorsairLedId.F2;
        public const CorsairLedId F3 = CorsairLedId.F3;
        public const CorsairLedId F4 = CorsairLedId.F4;
        public const CorsairLedId F5 = CorsairLedId.F5;
        public const CorsairLedId F6 = CorsairLedId.F6;
        public const CorsairLedId F7 = CorsairLedId.F7;
        public const CorsairLedId F8 = CorsairLedId.F8;
        public const CorsairLedId F9 = CorsairLedId.F9;
        public const CorsairLedId F10 = CorsairLedId.F10;
        public const CorsairLedId F11 = CorsairLedId.F11;
        public const CorsairLedId GraveAccentAndTilde = CorsairLedId.GraveAccentAndTilde;
        public const CorsairLedId D1 = CorsairLedId.D1;
        public const CorsairLedId D2 = CorsairLedId.D2;
        public const CorsairLedId D3 = CorsairLedId.D3;
        public const CorsairLedId D4 = CorsairLedId.D4;
        public const CorsairLedId D5 = CorsairLedId.D5;
        public const CorsairLedId D6 = CorsairLedId.D6;
        public const CorsairLedId D7 = CorsairLedId.D7;
        public const CorsairLedId D8 = CorsairLedId.D8;
        public const CorsairLedId D9 = CorsairLedId.D9;
        public const CorsairLedId D0 = CorsairLedId.D0;
        public const CorsairLedId MinusAndUnderscore = CorsairLedId.MinusAndUnderscore;
        public const CorsairLedId Tab = CorsairLedId.Tab;
        public const CorsairLedId Q = CorsairLedId.Q;
        public const CorsairLedId W = CorsairLedId.W;
        public const CorsairLedId E = CorsairLedId.E;
        public const CorsairLedId R = CorsairLedId.R;
        public const CorsairLedId T = CorsairLedId.T;
        public const CorsairLedId Y = CorsairLedId.Y;
        public const CorsairLedId U = CorsairLedId.U;
        public const CorsairLedId I = CorsairLedId.I;
        public const CorsairLedId O = CorsairLedId.O;
        public const CorsairLedId P = CorsairLedId.P;
        public const CorsairLedId BracketLeft = CorsairLedId.BracketLeft;
        public const CorsairLedId CapsLock = CorsairLedId.CapsLock;
        public const CorsairLedId A = CorsairLedId.A;
        public const CorsairLedId S = CorsairLedId.S;
        public const CorsairLedId D = CorsairLedId.D;
        public const CorsairLedId F = CorsairLedId.F;
        public const CorsairLedId G = CorsairLedId.G;
        public const CorsairLedId H = CorsairLedId.H;
        public const CorsairLedId J = CorsairLedId.J;
        public const CorsairLedId K = CorsairLedId.K;
        public const CorsairLedId L = CorsairLedId.L;
        public const CorsairLedId SemicolonAndColon = CorsairLedId.SemicolonAndColon;
        public const CorsairLedId ApostropheAndDoubleQuote = CorsairLedId.ApostropheAndDoubleQuote;
        public const CorsairLedId LeftShift = CorsairLedId.LeftShift;
        public const CorsairLedId NonUsBackslash = CorsairLedId.NonUsBackslash;
        public const CorsairLedId Z = CorsairLedId.Z;
        public const CorsairLedId X = CorsairLedId.X;
        public const CorsairLedId C = CorsairLedId.C;
        public const CorsairLedId V = CorsairLedId.V;
        public const CorsairLedId B = CorsairLedId.B;
        public const CorsairLedId N = CorsairLedId.N;
        public const CorsairLedId M = CorsairLedId.M;
        public const CorsairLedId CommaAndLessThan = CorsairLedId.CommaAndLessThan;
        public const CorsairLedId PeriodAndBiggerThan = CorsairLedId.PeriodAndBiggerThan;
        public const CorsairLedId SlashAndQuestionMark = CorsairLedId.SlashAndQuestionMark;
        public const CorsairLedId LeftCtrl = CorsairLedId.LeftCtrl;
        public const CorsairLedId LeftGui = CorsairLedId.LeftGui;
        public const CorsairLedId LeftAlt = CorsairLedId.LeftAlt;
        public const CorsairLedId Lang2 = CorsairLedId.Lang2;
        public const CorsairLedId Space = CorsairLedId.Space;
        public const CorsairLedId Lang1 = CorsairLedId.Lang1;
        public const CorsairLedId International2 = CorsairLedId.International2;
        public const CorsairLedId RightAlt = CorsairLedId.RightAlt;
        public const CorsairLedId RightGui = CorsairLedId.RightGui;
        public const CorsairLedId Application = CorsairLedId.Application;
        public const CorsairLedId LedProgramming = CorsairLedId.LedProgramming;
        public const CorsairLedId Brightness = CorsairLedId.Brightness;
        public const CorsairLedId F12 = CorsairLedId.F12;
        public const CorsairLedId PrintScreen = CorsairLedId.PrintScreen;
        public const CorsairLedId ScrollLock = CorsairLedId.ScrollLock;
        public const CorsairLedId PauseBreak = CorsairLedId.PauseBreak;
        public const CorsairLedId Insert = CorsairLedId.Insert;
        public const CorsairLedId Home = CorsairLedId.Home;
        public const CorsairLedId PageUp = CorsairLedId.PageUp;
        public const CorsairLedId BracketRight = CorsairLedId.BracketRight;
        public const CorsairLedId Backslash = CorsairLedId.Backslash;
        public const CorsairLedId NonUsTilde = CorsairLedId.NonUsTilde;
        public const CorsairLedId Enter = CorsairLedId.Enter;
        public const CorsairLedId International1 = CorsairLedId.International1;
        public const CorsairLedId EqualsAndPlus = CorsairLedId.EqualsAndPlus;
        public const CorsairLedId International3 = CorsairLedId.International3;
        public const CorsairLedId Backspace = CorsairLedId.Backspace;
        public const CorsairLedId Delete = CorsairLedId.Delete;
        public const CorsairLedId End = CorsairLedId.End;
        public const CorsairLedId PageDown = CorsairLedId.PageDown;
        public const CorsairLedId RightShift = CorsairLedId.RightShift;
        public const CorsairLedId RightCtrl = CorsairLedId.RightCtrl;
        public const CorsairLedId UpArrow = CorsairLedId.UpArrow;
        public const CorsairLedId LeftArrow = CorsairLedId.LeftArrow;
        public const CorsairLedId DownArrow = CorsairLedId.DownArrow;
        public const CorsairLedId RightArrow = CorsairLedId.RightArrow;
        public const CorsairLedId WinLock = CorsairLedId.WinLock;
        public const CorsairLedId Mute = CorsairLedId.Mute;
        public const CorsairLedId Stop = CorsairLedId.Stop;
        public const CorsairLedId ScanPreviousTrack = CorsairLedId.ScanPreviousTrack;
        public const CorsairLedId PlayPause = CorsairLedId.PlayPause;
        public const CorsairLedId ScanNextTrack = CorsairLedId.ScanNextTrack;
        public const CorsairLedId NumLock = CorsairLedId.NumLock;
        public const CorsairLedId KeypadSlash = CorsairLedId.KeypadSlash;
        public const CorsairLedId KeypadAsterisk = CorsairLedId.KeypadAsterisk;
        public const CorsairLedId KeypadMinus = CorsairLedId.KeypadMinus;
        public const CorsairLedId KeypadPlus = CorsairLedId.KeypadPlus;
        public const CorsairLedId KeypadEnter = CorsairLedId.KeypadEnter;
        public const CorsairLedId Keypad7 = CorsairLedId.Keypad7;
        public const CorsairLedId Keypad8 = CorsairLedId.Keypad8;
        public const CorsairLedId Keypad9 = CorsairLedId.Keypad9;
        public const CorsairLedId KeypadComma = CorsairLedId.KeypadComma;
        public const CorsairLedId Keypad4 = CorsairLedId.Keypad4;
        public const CorsairLedId Keypad5 = CorsairLedId.Keypad5;
        public const CorsairLedId Keypad6 = CorsairLedId.Keypad6;
        public const CorsairLedId Keypad1 = CorsairLedId.Keypad1;
        public const CorsairLedId Keypad2 = CorsairLedId.Keypad2;
        public const CorsairLedId Keypad3 = CorsairLedId.Keypad3;
        public const CorsairLedId Keypad0 = CorsairLedId.Keypad0;
        public const CorsairLedId KeypadPeriodAndDelete = CorsairLedId.KeypadPeriodAndDelete;
        public const CorsairLedId G1 = CorsairLedId.G1;
        public const CorsairLedId G2 = CorsairLedId.G2;
        public const CorsairLedId G3 = CorsairLedId.G3;
        public const CorsairLedId G4 = CorsairLedId.G4;
        public const CorsairLedId G5 = CorsairLedId.G5;
        public const CorsairLedId G6 = CorsairLedId.G6;
        public const CorsairLedId G7 = CorsairLedId.G7;
        public const CorsairLedId G8 = CorsairLedId.G8;
        public const CorsairLedId G9 = CorsairLedId.G9;
        public const CorsairLedId G10 = CorsairLedId.G10;
        public const CorsairLedId VolumeUp = CorsairLedId.VolumeUp;
        public const CorsairLedId VolumeDown = CorsairLedId.VolumeDown;
        public const CorsairLedId MR = CorsairLedId.MR;
        public const CorsairLedId M1 = CorsairLedId.M1;
        public const CorsairLedId M2 = CorsairLedId.M2;
        public const CorsairLedId M3 = CorsairLedId.M3;
        public const CorsairLedId G11 = CorsairLedId.G11;
        public const CorsairLedId G12 = CorsairLedId.G12;
        public const CorsairLedId G13 = CorsairLedId.G13;
        public const CorsairLedId G14 = CorsairLedId.G14;
        public const CorsairLedId G15 = CorsairLedId.G15;
        public const CorsairLedId G16 = CorsairLedId.G16;
        public const CorsairLedId G17 = CorsairLedId.G17;
        public const CorsairLedId G18 = CorsairLedId.G18;
        public const CorsairLedId International5 = CorsairLedId.International5;
        public const CorsairLedId International4 = CorsairLedId.International4;
        public const CorsairLedId Fn = CorsairLedId.Fn;
        public const CorsairLedId Logo = CorsairLedId.Logo;
    }
}
